### ISSUE TITLE
DB Unicode error: SAWarning: Unicode type received non-unicode bind param value 'SIMPLEMARKETMAKING'.

### ISSUE THREAD

**Issue by mattstone** [garethdmm/gryphon#22]
Hello,

Thanks for the app - looks really interesting.

I've just installed it and attempted to run the simple_market_making strategy.

I'm getting this error - full trace below.

SAWarning: Unicode type received non-unicode bind param value 'SIMPLEMARKETMAKING'.

Do I need to setup the MYSQL DB with a specific encoding?

---- Full Trace ----

(venv) zen:gryphon matt$ gryphon-exec strategy simple_market_making --builtin --exchange BITSTAMP_BTC_USD
INFO: Running strategy simple_market_making with configuration={'platform': {'audit': None, 'execute': False, 'config_file': None, 'sentry': None, 'strategy': 'simple_market_making', 'builtin': True, 'emerald': None, 'heartbeat': None}, 'strategy': {'tick_sleep': None, 'exchange': 'BITSTAMP_BTC_USD'}, 'exchanges': {}}
INFO:cement:app:gryphon-fury:Running strategy simple_market_making with configuration={'platform': {'audit': None, 'execute': False, 'config_file': None, 'sentry': None, 'strategy': 'simple_market_making', 'builtin': True, 'emerald': None, 'heartbeat': None}, 'strategy': {'tick_sleep': None, 'exchange': 'BITSTAMP_BTC_USD'}, 'exchanges': {}}
INFO:gryphon.execution.live_runner:live_run(simple_market_making, False)
INFO:gryphon.execution.harness.harness:[HARNESS_SETUP] (25/06/19 13:28:41 UTC) The following exchanges will be tradable: []

SimpleMarketMaking
/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:273: SAWarning: Unicode type received non-unicode bind param value 'SIMPLEMARKETMAKING'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),),
INFO:gryphon.execution.harness.harness:[SimpleMarketMaking] (25/06/19 13:28:41 UTC) Open position: BTC 0.00000000
INFO:gryphon.execution.harness.harness:[SimpleMarketMaking] (25/06/19 13:28:41 UTC) Available balances:
INFO:gryphon.execution.harness.harness:[SimpleMarketMaking] (25/06/19 13:28:41 UTC) Open Orders:
ERROR:gryphon.execution.live_runner:[TypeError] string indices must be integers
Traceback (most recent call last):
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/execution/live_runner.py", line 281, in live_run
    harness.tick()
  File "harness.pyx", line 161, in gryphon.execution.harness.harness.Harness.tick (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/execution/harness/harness.c:3195)
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/util/profile.py", line 59, in inner
    t, result = timeit.timeit(run_func, number=1)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer).timeit(number)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/timeit.py", line 202, in timeit
    timing = self.inner(it, self.timer)
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/util/monkeypatch_timeit.py", line 14, in inner
    retval = _func()
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/util/profile.py", line 57, in run_func
    return func(*args, **kwargs)
  File "harness.pyx", line 169, in gryphon.execution.harness.harness.Harness.tick_algo (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/execution/harness/harness.c:3394)
  File "simple_market_making.pyx", line 41, in gryphon.execution.strategies.builtin.simple_market_making.SimpleMarketMaking.tick (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/execution/strategies/builtin/simple_market_making.c:1530)
  File "exchange_coordinator.pyx", line 378, in gryphon.execution.harness.exchange_coordinator.ExchangeCoordinator.cancel_all_open_orders (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/execution/harness/exchange_coordinator.c:6923)
  File "exchange_api_wrapper.pyx", line 164, in gryphon.lib.exchange.exchange_api_wrapper.ExchangeAPIWrapper.cancel_all_open_orders (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/lib/exchange/exchange_api_wrapper.c:4500)
  File "exchange_api_wrapper.pyx", line 138, in gryphon.lib.exchange.exchange_api_wrapper.ExchangeAPIWrapper.get_open_orders (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/lib/exchange/exchange_api_wrapper.c:3902)
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/exchange/bitstamp_btc_usd.py", line 307, in get_open_orders_resp
    if raw_order['type'] == '0':
TypeError: string indices must be integers
INFO:gryphon.execution.live_runner:handle_exception succeeded, full speed ahead

SimpleMarketMaking
INFO:gryphon.execution.harness.harness:[SimpleMarketMaking] (25/06/19 13:28:47 UTC) Open position: BTC 0.00000000
INFO:gryphon.execution.harness.harness:[SimpleMarketMaking] (25/06/19 13:28:47 UTC) Available balances:
INFO:gryphon.execution.harness.harness:[SimpleMarketMaking] (25/06/19 13:28:47 UTC) Open Orders:
ERROR:gryphon.execution.live_runner:[TypeError] string indices must be integers
Traceback (most recent call last):
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/execution/live_runner.py", line 281, in live_run
    harness.tick()
  File "harness.pyx", line 161, in gryphon.execution.harness.harness.Harness.tick (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/execution/harness/harness.c:3195)
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/util/profile.py", line 59, in inner
    t, result = timeit.timeit(run_func, number=1)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/timeit.py", line 237, in timeit
    return Timer(stmt, setup, timer).timeit(number)
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/timeit.py", line 202, in timeit
    timing = self.inner(it, self.timer)
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/util/monkeypatch_timeit.py", line 14, in inner
    retval = _func()
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/util/profile.py", line 57, in run_func
    return func(*args, **kwargs)
  File "harness.pyx", line 169, in gryphon.execution.harness.harness.Harness.tick_algo (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/execution/harness/harness.c:3394)
  File "simple_market_making.pyx", line 41, in gryphon.execution.strategies.builtin.simple_market_making.SimpleMarketMaking.tick (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/execution/strategies/builtin/simple_market_making.c:1530)
  File "exchange_coordinator.pyx", line 378, in gryphon.execution.harness.exchange_coordinator.ExchangeCoordinator.cancel_all_open_orders (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/execution/harness/exchange_coordinator.c:6923)
  File "exchange_api_wrapper.pyx", line 164, in gryphon.lib.exchange.exchange_api_wrapper.ExchangeAPIWrapper.cancel_all_open_orders (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/lib/exchange/exchange_api_wrapper.c:4500)
  File "exchange_api_wrapper.pyx", line 138, in gryphon.lib.exchange.exchange_api_wrapper.ExchangeAPIWrapper.get_open_orders (/Users/matt/.pyxbld/temp.macosx-10.14-x86_64-2.7/pyrex/gryphon/lib/exchange/exchange_api_wrapper.c:3902)
  File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/exchange/bitstamp_btc_usd.py", line 307, in get_open_orders_resp
    if raw_order['type'] == '0':
TypeError: string indices must be integers
INFO:gryphon.execution.live_runner:handle_exception succeeded, full speed ahead
^CINFO:gryphon.execution.live_runner:Setting Warm Shutdown Flag

SimpleMarketMaking
INFO:gryphon.execution.live_runner:Initiating Warm Shutdown
INFO:gryphon.execution.live_runner:Warm Shutdown Complete
(venv) zen:gryphon matt$

**Comment by mattstone** [comment]
You can also see another error in the trace.

File "/Users/matt/projects/internetschminternet/gryphon/venv/lib/python2.7/site-packages/gryphon/lib/exchange/bitstamp_btc_usd.py", line 307, in get_open_orders_resp
if raw_order['type'] == '0':
TypeError: string indices must be integers
INFO:gryphon.execution.live_runner:handle_exception succeeded, full speed ahead

The code does not crash, it just keeps throwing the above error.

**Comment by garethdmm** [comment]
Hey Matt, the error is happening in the web call to bitstamp to get your current open orders. Do you have your exchange credentials set up in your `.env` file?

One way to test the exchange connection would be to open the gryphon command line and call the open orders function directly.

```
$ gryphon-cli
> b.get_open_orders()
```

[This all is assuming you've migrated your trading database and started an exchange ledger for Bitstamp.]

**Comment by mattstone** [comment]
Thanks for your reply Gareth.

I have this in my .env file

BITSTAMP_BTC_USD_CLIENT_ID=[My Client Id]
BITSTAMP_BTC_USD_API_KEY=[My Api Key]
BITSTAMP_BTC_USD_API_SECRET=[My Api Secret]

& I've run the migrations

when I run gryphon-cli I get this message
INFO:gryphon.execution.console:Couldn't get a gds session. Probably missing credentials or GDS isn't set up.
Python 2.7.16 (default, Jun 19 2019, 07:40:37) 
Type "copyright", "credits" or "license" for more information.

IPython 5.7.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

I've got the credentials in the .env file - do I need to compile from source and install GDS?

Also..

This link https://gryphon.readthedocs.io/en/latest/usage.html says the Bitstamp variables are..
BITSTAMP_BTC_USD_API_KEY=[YOUR KEY]
BITSTAMP_BTC_USD_API_SECRET=[YOUR SECRET]
BITSTAMP_BTC_USD_API_PASSPHRASE=[YOUR PASSPHRASE]

Whilst this link https://gryphon.readthedocs.io/en/latest/environment.html#environment-exchanges says the Bitstamp variables  are

BITSTAMP_BTC_USD_API_SECRET
BITSTAMP_BTC_USD_API_KEY
BITSTAMP_BTC_USD_CLIENT_ID

I just point this out as I can't find a PASSPHRASE anywhere on the Bitstamp API documentation

**Comment by garethdmm** [comment]
Ah, yeah that PASSPHRASE is likely a typo. Thanks for catching it. API_SECRET, API_KEY, CLIENT_ID should be the right parameters.

No, you don't have to run GDS. Just to confirm, you don't get the prompt after that warning when you run `gryphon-cli`?

I'm still pretty sure this is a credential issue. The Exchange library has a habit of hiding the true source of errors.

Here's two easy things to check, hopefully it's one of those:
- Maybe it's as simple as you've reversed API_KEY and API_PASSPHRASE accidentally?
- You could also try putting quotes around the keys or not, this doesn't appear to matter on my system but it could be your system is different

If that doesn't work, here's a more in-depth debug method.
1) Download the project (https://github.com/garethdmm/gryphon/archive/master.zip). After unzipping it, run `pip install -e [directory]` where `[directory]` is the root of the unzipped file.
2) Add some print statements in the bitstamp_btc_usd wrapper (gryphon/lib/exchange/bitstamp_btc_usd.py) to figure out exactly what the exchange is saying back to you. I'd recommend line 77/78:
```
 77         response = super(BitstampBTCUSDExchange, self).resp(req)
 78         print str(response)
```
And maybe 303-305
303         raw_open_orders = self.resp(req)
304         open_orders = []
305         print str(raw_open_orders)

That should print to console the raw json that bitstamp is returning to you, which should give you a better idea about what they don't like.

**Comment by garethdmm** [comment]
To answer your earlier question, Gryphon has always been run with utf8 db encodings. I wouldn't be able to predict how it will behave using other encodings, but I'm still pretty sure this is an exchange API connection issue.

**Comment by mattstone** [comment]
Thanks for all your help.

You were right. It was a permissions issue.

Your debugging hints were exactly what I needed.

After contacting Bitstamp, they sorted it out.
