### ISSUE TITLE
make_exchange_datas_from_keys assertion

### ISSUE THREAD

**Issue by asmodehn** [garethdmm/gryphon#25]
This: https://github.com/garethdmm/gryphon/blob/master/gryphon/lib/exchange/exchange_factory.py#L145

keeps asserting, when using the dashboard (Just clicking on "trading" -> "status" for example)
I am guessing this is because I did not setup a bank account ?

So I get (with a small debug change):
```
Traceback (most recent call last):
  File "/home/alexv/.virtualenvs/gryphon2/local/lib/python2.7/site-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/alexv/.virtualenvs/gryphon2/local/lib/python2.7/site-packages/tornado/web.py", line 2898, in wrapper
    return method(self, *args, **kwargs)
  File "/home/alexv/Projects/gryphon/gryphon/dashboards/handlers/status.py", line 31, in get
    bank_accounts = self.get_trading_bank_accounts()
  File "/home/alexv/Projects/gryphon/gryphon/dashboards/handlers/status.py", line 178, in get_trading_bank_accounts
    self.trading_db,
  File "/home/alexv/Projects/gryphon/gryphon/lib/exchange/exchange_factory.py", line 102, in make_exchange_data_from_key
    exchange_datas = make_exchange_datas_from_keys(keys, db)
  File "/home/alexv/Projects/gryphon/gryphon/lib/exchange/exchange_factory.py", line 145, in make_exchange_datas_from_keys
    assert len(exchange_datas) == len(pair_names), str(exchange_datas) + " " + str(pair_names)
AssertionError: [] ['BMO_USD']
```

However I would like the dashboard to be usable, even without any bank account setup.
I am wondering where I should start looking if I want to fix that ?
Thank you.

**Comment by garethdmm** [comment]
Integrating bank accounts is supposed to be an optional feature, so this certainly shouldn't be happening. I'll take a look later today.

**Comment by asmodehn** [comment]
I digged a little bit, and this https://github.com/garethdmm/gryphon/blob/master/gryphon/dashboards/handlers/status.py#L171 looks like it should come from a configuration, somehow set up when we configure bank accounts.
Putting an empty list there solves my issue, but is obviously not a long term solution.

**Comment by garethdmm** [comment]
Does this issue happen on other dashboards or just Status?

**Comment by asmodehn** [comment]
Actually it happens only Status. I just checked all the menu items.
Seems expected, as I can find it used only from `GryphonStatusHandler`

I have other errors in other places, but I ll create separate issues, when I'll isolate a problem.
I m trying to investigate and fix them one at a time, I might have gotten some things wrong when setting up everything...

In any case, thanks a lot for the help !

**Comment by garethdmm** [comment]
Ok. Yeah, /status is borderline deprecated right now, I'm not sure if it adds much value that isn't present in other dashboards, or if it does it could use a re-design. Maybe I'll take it out of the navbar for now so other people don't get distracted.
