### ISSUE TITLE
Out of date GDS dictionary

### ISSUE THREAD

**Issue by matteosantama** [garethdmm/gryphon#45]
When I try to run GDS I get the following error,

 `12:30:33 PRODUCER.1           | INFO:emerald-havoc-producer:['BITSTAMP_BTC_USD', 'COINBASE_BTC_USD', 'GEMINI_BTC_USD']
12:30:33 PRODUCER.1           | Traceback (most recent call last):
12:30:33 PRODUCER.1           |   File "runt.py", line 80, in <module>
12:30:33 PRODUCER.1           |     main()
12:30:33 PRODUCER.1           |   File "runt.py", line 68, in main
12:30:33 PRODUCER.1           |     TradesPollTask(exchanges=non_orderbook_exchanges).start_task()
12:30:33 PRODUCER.1           |   File "/home/matteo/Desktop/gryphon/gryphon/data_service/trades_poll_task.py", line 33, in __init__
12:30:33 PRODUCER.1           |     self.pollers = [exchange_pollers[ex] for ex in exchanges]
12:30:33 PRODUCER.1           | KeyError: 'GEMINI_BTC_USD'
`

When I checked the code in trades_poll_task.py, it looks like the dictionary contains the key 'GEMINI' but not 'GEMINI_BTC_USD'. I'm not sure if the fix is as simple as updating the key.

**Comment by garethdmm** [comment]
The cause of this is a dictionary with exchange keys in gryphon/data_service/trades_poll_task.py that needs updating. Should be a simple fix if anyone wants to take it on.
