### ISSUE TITLE
Bitstamp : subaccount API invalid signature

### ISSUE THREAD

**Issue by asmodehn** [garethdmm/gryphon#49]
```
(gryphon2)alexv@pop-os:/opt/Projects/gryphon-strategies$ gryphon-exec script reset_balance --exchange_name bitstamp_btc_eur
{u'status': u'error', u'reason': u'Invalid signature', u'code': u'API0005'}
Traceback (most recent call last):
  File "/home/alexv/.virtualenvs/gryphon2/bin/gryphon-exec", line 11, in <module>
    load_entry_point('gryphon', 'console_scripts', 'gryphon-exec')()
  File "/opt/Projects/gryphon/gryphon/execution/app.py", line 544, in main
    app.run()
  File "/home/alexv/.virtualenvs/gryphon2/local/lib/python2.7/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/home/alexv/.virtualenvs/gryphon2/local/lib/python2.7/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/home/alexv/.virtualenvs/gryphon2/local/lib/python2.7/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/opt/Projects/gryphon/gryphon/execution/app.py", line 437, in default
    main_function(script_arguments=script_arguments, execute=execute)
  File "/opt/Projects/gryphon/gryphon/execution/scripts/reset_balance.py", line 159, in main
    fix_balance_issues_for_exchange(exchange_name, execute)
  File "/opt/Projects/gryphon/gryphon/execution/scripts/reset_balance.py", line 137, in fix_balance_issues_for_exchange
    exchange_balance = exchange.get_balance()
  File "exchange_api_wrapper.pyx", line 203, in gryphon.lib.exchange.exchange_api_wrapper.ExchangeAPIWrapper.get_balance (/home/alexv/.pyxbld/temp.linux-x86_64-2.7/pyrex/gryphon/lib/exchange/exchange_api_wrapper.c:5374)
  File "/opt/Projects/gryphon/gryphon/lib/exchange/bitstamp_btc_usd.py", line 232, in get_balance_resp
    'Balance missing expected keys',
gryphon.lib.exchange.exceptions.ExchangeAPIErrorException: [BITSTAMP_BTC_EUR] Balance missing expected keys
```

Anyone else having the same issue ? It used to work for main account... Any hint ?

**Comment by garethdmm** [comment]
I found one bug on a related project where the user had their CLIENT_ID set up incorrectly, I think you should be still using the CLIENT_ID of the main account.

**Comment by garethdmm** [comment]
I also noticed that you have to 'activate' api keys on sub accounts, which is a button next to the key. Maybe that is the issue?

**Comment by asmodehn** [comment]
The key was activated (error code is API0001 if it isnt)
The issue was indeed that I used the subaccount client, but the main account client id (with sub account keys) works.
