### ISSUE TITLE
AttributeError: type object 'IOLoop' has no attribute 'initialized'

### ISSUE THREAD

**Issue by tdudz** [garethdmm/gryphon#75]
Whenever i run the dashboard server and navigate to the "Simple Market Making" tab under "Trading" in the dashboard, i get the following error:

`/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/sqlalchemy/sql/sqltypes.py:242: SAWarning: Unicode type received non-unicode bind param value 'MULTI'. (this warning may be suppressed after 10 occurrences)
  (util.ellipses_string(value),))
ERROR:tornado.application:Uncaught exception GET /strategies/manual (::1)
HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/strategies/manual', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornado/web.py", line 3006, in wrapper
    return method(self, *args, **kwargs)
  File "/Users/tdudz/gryphon/gryphon/dashboards/handlers/strategies/strategy.py", line 63, in get
    self.render_template('strategy.html', args=template_args)
  File "/Users/tdudz/gryphon/gryphon/dashboards/handlers/admin_base.py", line 109, in render_template
    return self.render(template, **kwargs)
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornado/web.py", line 766, in render
    html = self.render_string(template_name, **kwargs)
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornado/web.py", line 907, in render_string
    return t.generate(**namespace)
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornado/template.py", line 346, in generate
    return execute()
  File "templates/strategy_html.generated.py", line 107, in _tt_execute
    _tt_tmp = '%s %.2f' % (args['open_pl'].currency, args['open_pl'].amount)  # templates/strategy.html:51 (via templates/base.html:207)
AttributeError: 'NoneType' object has no attribute 'currency'
ERROR:tornado.application:Exception in exception handler
Traceback (most recent call last):
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornado/web.py", line 1597, in _execute
    self._handle_request_exception(e)
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornado/web.py", line 1650, in _handle_request_exception
    self.send_error(500, exc_info=sys.exc_info())
  File "/Users/tdudz/gryphon/gryphon/dashboards/handlers/base.py", line 67, in send_error
    tornado_toad.post_notice(exception, request=request_data)
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornadotoad/api.py", line 28, in post_notice
    self._send(url, body=body, headers={'Content-Type': 'text/xml'})
  File "/Users/tdudz/.local/share/virtualenvs/gryphon-qObydNvD/lib/python2.7/site-packages/tornadotoad/api.py", line 141, in _send
    if tornado.ioloop.IOLoop.initialized():
AttributeError: type object 'IOLoop' has no attribute 'initialized'`

**Comment by tdudz** [comment]
I managed to fix the second error by downgrading `tornado` to version 4.5.3 as suggested in a different issue. However, the other issue above, regarding `AttributeError: 'NoneType' object has no attribute 'currency'` still persists, and the dashboard now shows `500 ERROR`.

**Comment by tdudz** [comment]
update #2: i fixed the `500 ERROR` by pulling a commit that fixed the `open_pl` issue being `None`. 

Are the dashboards supposed to show anything when running with `execute=False`?
