### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'

### ISSUE THREAD

**Issue by RED29** [garethdmm/gryphon#77]
I got an error after running this command;
(grybot)$ gryphon-exec run-migrations --database trading --execute
Python2 is correctly installed all other modules.

--||--
(grybot)$ gryphon-exec run-migrations --database trading --execute
INFO:gryphon.execution.controllers.run_migrations:Migrating the trading database
Traceback (most recent call last):
  File "/usr/local/bin/gryphon-exec", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/app.py", line 544, in main
    app.run()
  File "/usr/local/lib/python2.7/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python2.7/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/app.py", line 491, in default
    run_migrations.main(target_db, execute)
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/controllers/run_migrations.py", line 63, in main
    run_migrations(target_db)
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/controllers/run_migrations.py", line 50, in run_migrations
    command.upgrade(alembic_cfg, 'head')
  File "/usr/local/lib/python2.7/site-packages/alembic/command.py", line 124, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/site-packages/alembic/script.py", line 193, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/site-packages/alembic/util.py", line 177, in load_python_file
    module = load_module(module_id, path)
  File "/usr/local/lib/python2.7/site-packages/alembic/compat.py", line 39, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/migrations/env.py", line 98, in <module>
    run_migrations_online()
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/migrations/env.py", line 76, in run_migrations_online
    engine = create_engine(os.environ.get('TRADING_DB_CRED'))
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 443, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 56, in create
    plugins = u._instantiate_plugins(kwargs)
**AttributeError: 'NoneType' object has no attribute '_instantiate_plugins'**
--||--

**Comment by maxima-us** [comment]
I had a similar issue when adding new tables to the trading database. Here is what solved it :
change `engine = create_engine(os.environ.get('TRADING_DB_CRED'))` to : 
`engine = engine_from_config(           config.get_section(config.config_ini_section),
 prefix='sqlalchemy.', poolclass=pool.NullPool)` in migrations/env.py.

Hope this helps

**Comment by RED29** [comment]
Hi @maxima-us thanks for helping out this issue. I have tried and now I get another error;

--||--
**/grybot$ gryphon-exec run-migrations --database trading --execute**
INFO:gryphon.execution.controllers.run_migrations:Migrating the trading database
Traceback (most recent call last):
  File "/usr/local/bin/gryphon-exec", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/app.py", line 544, in main
    app.run()
  File "/usr/local/lib/python2.7/site-packages/cement/core/foundation.py", line 882, in run
    return_val = self.controller._dispatch()
  File "/usr/local/lib/python2.7/site-packages/cement/core/controller.py", line 471, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/site-packages/cement/core/controller.py", line 477, in _dispatch
    return func()
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/app.py", line 491, in default
    run_migrations.main(target_db, execute)
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/controllers/run_migrations.py", line 63, in main
    run_migrations(target_db)
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/controllers/run_migrations.py", line 50, in run_migrations
    command.upgrade(alembic_cfg, 'head')
  File "/usr/local/lib/python2.7/site-packages/alembic/command.py", line 124, in upgrade
    script.run_env()
  File "/usr/local/lib/python2.7/site-packages/alembic/script.py", line 193, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/usr/local/lib/python2.7/site-packages/alembic/util.py", line 177, in load_python_file
    module = load_module(module_id, path)
  File "/usr/local/lib/python2.7/site-packages/alembic/compat.py", line 39, in load_module
    return imp.load_source(module_id, path, fp)
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/migrations/env.py", line 98, in <module>
    run_migrations_online()
  File "/usr/local/lib/python2.7/site-packages/gryphon/execution/migrations/env.py", line 81, in run_migrations_online
    poolclass=pool.NullPool)
  File "/usr/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 485, in engine_from_config
    url = options.pop("url")
**KeyError: 'url'**
--||--

Thanks!
